import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "~/components/theme-provider";
import { cn } from "~/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Dots and Boxes",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					inter.variable,
				)}
				style={{
					backgroundSize: "40px 40px",
					backgroundImage: `repeating-linear-gradient(0deg, hsl(var(--accent) / 0.15), hsl(var(--accent) / 0.15) 1px, transparent 0, transparent 40px), 
													repeating-linear-gradient(90deg, hsl(var(--accent) / 0.15), hsl(var(--accent) / 0.15) 1px, transparent 0, transparent 40px)`,
					boxShadow: "inset 0px 0px 0px 1px hsl(var(--accent) / 0.15)",
				}}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					enableColorScheme
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
